[package]
name = "sum_count_files"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
failure = "=0.1.0"
filebuffer = "=0.3.0"
glob = "=0.2.11"
log = "=0.3.8"
log4rs = "=0.7.0"
rayon = "=0.9.0"
structopt = "=0.1.5"
structopt-derive = "=0.1.5"